#!/groovy

node('master') {

  stage 'load groovy script'
  echo "-- lets load a groovy script so that we can use its methods."
  echo "-- this is a great approach to minimize job-specific configuration and maximize code reuse."
  echo "-- load paths are relative to the directory your current script is in. "
  load '../scripts/common.groovy'

  stage 'say hello'
  echo "-- this is a stage. A stage is a logical separation of your build pipeline."
  echo "-- stages can be used to separate out distinct but connected components of your pipeline."

  stage 'say your name'
  echo "I am node ${env.NODE_NAME}"

}
